#! /bin/bash

sudo apt-get install python-dev
sudo apt-key add ../skewed.public.key


# LibBoost -- Fast Compilation
#    deb http://ppa.launchpad.net/mapnik/boost/ubuntu precise main
#    deb-src http://ppa.launchpad.net/mapnik/boost/ubuntu precise main
sudo apt-get install libboost-all-dev

# NumPy
sudo apt-get install python-numpy

# SciPy
sudo apt-get install python-scipy

# Add CGAL to sources.list
#      deb ftp://ftp.mpi-sb.mpg.de/pub/outgoing/CGAL/debian squeeze main contrib non-free
#      deb-src ftp://ftp.mpi-sb.mpg.de/pub/outgoing/CGAL/debian squeeze main contrib non-free
sudo apt-get install libcgal-dev

# sparsehash -- C++ HashMap Implementation
sudo apt-get install sparsehash

# Cairo -- 2D Graphics Library
sudo apt-get install libcairo2

# PyCairo -- Python Bindings for Cairo
sudo apt-get install python-cairo

# MatPlotLib -- Python Plotting System
sudo apt-get install python-matplotlib

# GraphViz -- Graph Visualization
sudo apt-get install graphviz

# Add graph-tool to sources.list
#      deb http://downloads.skewed.de/apt/precise precise universe
#      deb-src http://downloads.skewed.de/apt/precise precise universe
sudo apt-get install python-graph-tool